Repository datalad/datalad-installer, pull requests merged in 2021-06, with the labels that each got.

#67 [DATALAD RUNCMD] codespell is lucky to find a typo
  src/datalad_installer.py
Labels: internal

#69 Add "dmg" installation method for git-annex
  README.rst
  src/datalad_installer.py
  test/test_options.py
Labels: minor

#72 Delete a certain tempfile once we're done with it
  src/datalad_installer.py
Labels: patch

#76 Add installation method for getting latest build of datalad/git-annex; rename datalad/git-annex to datalad/git-annex:tested
  README.rst
  src/datalad_installer.py
  test/test_options.py
  test/test_util.py
Labels: minor, release
