Repository datalad/datalad-installer, pull requests merged in 2021-07, with the labels that each got.

#73 Support installing git-annex .deb's to a given directory instead of system-wide
  README.rst
  src/datalad_installer.py
  test/test_options.py
Labels: minor, release

#78 Make miniconda error if conda is already installed; mark miniconda tests
  src/datalad_installer.py
  test/test_install.py
  tox.ini
Labels: patch, release

#79 Only run apt-based tests on systems with Apt, and likewise for brew
  test/test_install.py
Labels: release, tests

#80 Use newer build for OSX (from Catalina on GH actions, instead of Yosemite)
  src/datalad_installer.py
Labels: release

#83 Retry failed "conda install" commands
  src/datalad_installer.py
Labels: patch

#84 datalad/git-annex: Install commands that fail with WinError 740 are retried with elevation
  src/datalad_installer.py
Labels: patch, release
