Repository datalad/datalad-installer, pull requests merged in 2024-02, with the labels that each got.

#192 Assorted minor README improvements
  README.rst
Labels: documentation

#194 Always provide -y to apt-get install
  src/datalad_installer.py
Labels: patch, release

#195 Skip `--dev-pip` test on Python 3.7
  test/test_install.py
Labels: tests
